apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-cm
data:
# change ingress_gw to url of the istio-ingress gateway route,
# e.g. istio-ingressgateway-istio-system.example.com/
# if you want to change the /exchange, change the virtual service
# for the exchange service too.
  GW_ADDR: exchange-exchange.apps.na3.dev.nextcle.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: quay.io/redhattraining/ossm-frontend:1.0
          ports:
            - containerPort: 3000
          env:
            - name: REACT_APP_GW_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: frontend-cm
                  key: GW_ADDR
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend
---
apiVersion: v1
kind: Route
metadata:
  name: exchange
spec:
  to:
    kind: Service
    name: frontend
