{
 "title": "Demo Expenses Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Expense List Total Requests",
   "type": "stat",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "callsToExpenseList_total" }
   ]
  },
  {
   "title": "Calls to Expense Create",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "callsToExpenseCreate_total" }
   ]
  },
  {
   "title": "Expense List time to response",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "expenseListTimer_seconds_max" }
   ]
  },
  {
   "title": "Time to last call to list expenses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "timeToLastExpenseList" }
   ]
  }
 ]
}